### PR TITLE
[WIP] various improvements/move project to fullstack example

### PR DESCRIPTION
**Pull request by nopeless**
This is the final code for the moment. let me work on this for now (do not merge, branch will be force pushed at some point)

### CODE REVIEW

**Comment by alexander-gekov** [comment]
Hello, I have checked your pull request. All looks good, just wondering why use a separate express as an API server, when we have Nuxt already?

**Comment by nopeless** [comment]
> Hello, I have checked your pull request. All looks good, just wondering why use a separate express as an API server, when we have Nuxt already?

The separate express api server is emulating the movie api, not the api functionality of Nuxt's built in server. It is not necessary to run the express api server if you already have an api key for the movie api server. I wanted to introduce a fully self contained full-stack application for my colleague instead of having to rely on external back end services.

**Comment by nopeless** [comment]
there is WIP in the title. I forgot to mark as draft

**Comment by nopeless** [comment]
can you unmerge it

**Comment by alexander-gekov** [comment]
I reverted it. Feel free to create new one.

**Comment by nopeless** [comment]
Thanks

**Pull request merged**
